[project]
name = "dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "jupyterlab>=4.4.6",
    "pandas>=2.3.1",
    "seaborn>=0.13.2",
]
